version: "3.6"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./app:/var/www/html/
  apache:
    build: './apache2/'
    depends_on:
      - php
      - mysql
    networks:
      - backend
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html/
  mysql:
    image: mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  backend:
